/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    NavBar: typeof import('./src/components/nav/NavBar.vue')['default']
    PiwoCalculator: typeof import('./src/components/PiwoCalculator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
